### ISSUE TITLE
Checklist for migrating CIRM to new platform

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#2]
_Provision_
- [x] build off of repeatable recipes
- [x] get test data
- [x] upgrade to latest OS and system software

_Microscopy UI_
- [x] remove GO transfer
- [x] drop zoomify

_Hatrac_
- [x] deploy latest
- [x] use to store whole images (CZI) in hatrac (do not use for tiles)

_ERMrest_
- [x] deploy latest

_Chaise_
- [x] deploy latest

_IObox_
- [x] drop the CziConverter process
- [x] drop the GO transfer
- [x] post files to Hatrac (rather than GO transfer)

_ScanTiler_
- [x] remove the tiff to zoom conversion
- [x] add CZI to Dzi conversion
- could do this with simple psql queries rather than ermrest

_AuthN_
- [x] remove GO proxy for login
- [x] use webauthn + GO for login via Oauth process
- [x] whitelist dev/staging hosts at ISI
- [x] whitelist production host(s) at HSC
- [x] webauthn agent credential support (i.e., for IObox and Scantiler daemons)

_Database_
- [x] use denormalized views to improve presentation

**Comment by hongsudt** [comment]
@svoinea @robes do you want to get this done with 2016-03 milestone?

**Comment by robes** [comment]
@hongsudt yes

**Comment by hongsudt** [comment]
@svoinea since all the list items are checked, is this task done now?

**Comment by robes** [comment]
@svoinea is there a dev or staging server that we can visit to test this?

**Comment by svoinea** [comment]
cirm-dev.isrd.isi.edu and cirm-staging.isrd.isi.edu
For URL use /webcli and /chaise/search

**Comment by robes** [comment]
When going to the chaise/search/ interface. I’m not sure what I’m looking at. What is the ‘image’ table that I’m searching on?

**Comment by svoinea** [comment]
It's just a view containing most of the Scan columns extended with some columns from the Slide, Experiment and Specimen tables for which it belongs to.

The view definition is:

create view image as
select "Scan"."ID", "Scan"."Slide ID", "Scan"."Original Filename", 
'https://cirm-devel.misd.isi.edu/openseadragon-viewer/mview.html?url=https://cirm-devel.misd.isi.edu/data/' || replace("Scan"."Filename", '.czi', '/Brigh/ImageProperties.xml') "URI" , "Scan"."File Size", 
replace ("Scan"."Thumbnail", 'piranha.hsc.usc.edu/cirm-usc', 'cirm-devel.misd.isi.edu') "Thumbnail", "Scan"."Microscope", "Scan"."Camera", "Scan"."Objective", "Scan"."Exposure Time", "Scan"."Channels", "Scan"."Channel Name", "Scan"."Contrast Method", "Scan"."Magnification", "Scan"."Light Source Intensity", "Scan"."Image Size", "Scan"."Scaling (per pixel)", "Slide"."Seq.", "Slide"."Rev.", "Experiment"."Experiment Date", "Experiment"."Experiment Description", "Experiment"."Initials", "Experiment"."Experiment Type", "Experiment"."Probe", "Specimen"."Section Date", "Specimen"."Sample Name", "Specimen"."Species", "Specimen"."Age", "Specimen"."Tissue", "Specimen"."Gene", "Specimen"."Specimen Identifier" from "Scan", "Slide", "Experiment", "Specimen" where "Slide"."ID" = "Scan"."Slide ID" and "Slide"."Experiment ID" = "Experiment"."ID" and "Slide"."Specimen ID" = "Specimen"."ID";

**Comment by robes** [comment]
i've seen the servers up and running so we'll just close this master issue, and switch into the mode of opening smaller specific issues as we go.
